/*
 * Conciliador.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Conciliador.Standard.Http.Request;
namespace Conciliador.Standard
{
    internal partial class AuthUtility
    {
        /// <summary>
        /// Appends the necessary Custom Authentication credentials for making this authorized call
        /// </summary>
        /// <param name="request">The out going request to access the resource</param>        
        internal static void AppendCustomAuthParams(HttpRequest request)
        {
            // TODO: Add your custom authentication here
            // The following properties are available to use
			//     Configuration.AccessToken
            // 
            // ie. Add a header through:
            //     request.header("Key", "Value");
        }
    }
}
