/*
 * Conciliador.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using Conciliador.Standard.Controllers;
using Conciliador.Standard.Http.Client;
using Conciliador.Standard.Utilities;

namespace Conciliador.Standard
{
    public partial class ConciliadorClient
    {

        /// <summary>
        /// Singleton access to Acesso controller
        /// </summary>
        public AcessoController Acesso
        {
            get
            {
                return AcessoController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public ConciliadorClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public ConciliadorClient(string accessToken)
        {
            Configuration.AccessToken = accessToken;
        }
        #endregion
    }
}